-- Create review table
CREATE TABLE public.review (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_text CHARACTER VARYING,
    rating INT CHECK (rating BETWEEN 1 AND 5),
    account_id INTEGER NOT NULL,
    inv_id INTEGER NOT NULL,
    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create relationship to account table
ALTER TABLE public.review
    ADD CONSTRAINT fk_review_account
    FOREIGN KEY (account_id)
    REFERENCES public.account (account_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;

-- Create relationship to inventory table
ALTER TABLE public.review
    ADD CONSTRAINT fk_review_inventory
    FOREIGN KEY (inv_id)
    REFERENCES public.inventory (inv_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;
